In [2]:
import torch
import numpy as np

In [3]:
#1d array
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
#float형 텐서로 만들겠다.
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [6]:
print(t.dim()) #rank ->몇 개의 차원이 있니
print(t.shape) #shape
print(t.size()) #shape와 같음
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [7]:
#2d array
t = torch.FloatTensor([[1., 2., 3.],
                      [4., 5., 6.],
                      [7., 8., 9.],
                      [10., 11., 12.]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [8]:
print(t.dim())
print(t.size())
print(t[:, 1]) #두번째 것만 가져와라
print(t[:, 1].size())
print(t[:, :-1]) #맨마지막을 제외한 것을 가져와

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [9]:
#broadcasting
#두 텐서 간 크기가 같아야 한다 등 규칙이 있지만
#다른 크기의 행렬과 텐서를 연산할 수 있음.
#broadcasting이 이를 가능하게 해줌.
m1 = torch.FloatTensor([3, 3])
m2 = torch.FloatTensor([2, 2])
print(m1 + m2)

tensor([5., 5.])


In [11]:
#vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # 3-> [[3,3]]으로 자동으로 바꿔줌
print(m1 + m2)

tensor([[4., 5.]])


In [13]:
#텐서 간 연산에도 가능
# 2x1 vector + 1x2 vector
m1 = torch.FloatTensor([[1,2]]) #(1,2) -> (2,2) 따라서 [[1,2],[1,2]]
m2 = torch.FloatTensor([[3], [4]]) #(2,1) ->(2,2) 따라서 [[3,4]],[[3,4]]
print(m1 + m2)

'''
브로드캐스팅은 자동으로 되기 때문에 주의해야 함!
실수를 해서 다른 사이즈가 계산되면 원래의 계획과 달라진다!
프로그램이 어디서 잘못됐는가!를 모름
'''

tensor([[4., 5.],
        [5., 6.]])


In [17]:
#matrix multiplication

#일반적인 매트릭스 곱셈
m1 = torch.FloatTensor([[1,2], [3,4]])
m2 = torch.FloatTensor([[1], [2]])
print('shape of matrix1: ', m1.shape)
print('shape of matrix2: ', m2.shape)
print(m1.matmul(m2)) #매트릭스곱
print(m1.mul(m2)) #m2가 [1,1],[2,2]로 늘어남, 각각 1번째끼리 곱, 2번째끼리곱,...

shape of matrix1:  torch.Size([2, 2])
shape of matrix2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
tensor([[1., 2.],
        [6., 8.]])


In [19]:
#평균을 구하는 방법

t = torch.FloatTensor([1,2])
print(t.mean())

t = torch.LongTensor([1,2]) #롱 텐서에 대해서는 처리못함.
try:
    print(t.mean())
except Exception as exc:
    print(exc)

tensor(1.5000)
Can only calculate the mean of floating types. Got Long instead.


In [22]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)
print(t.mean(dim = 0)) #(2,2)->(1,2)로 평균을 낸다.열끼리 평균 냄(1열평균, 2열평균)
print(t.mean(dim = 1)) #(2,2)->(2,1)로 평균을 낸다.행끼리 평균 냄(1행평균, 2행평균)
print(t.mean(dim = -1))


tensor([[1., 2.],
        [3., 4.]])
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [25]:
#sum
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

print(t.sum()) #그냥 네 개의 값을 모두 더한 것
print(t.sum(dim = 0)) #axis = 0으로 sum해라
print(t.sum(dim = 1)) #axis = 1으로 sum해라
print(t.sum(dim = -1))

tensor([[1., 2.],
        [3., 4.]])
tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [31]:
#max and argmax

t = torch.FloatTensor([[1,2], [3,4]])
print(t)
print(t.max()) #4개 중에서 가장 큰 걸 찾아줘

print(t.max(dim = 0)) #axis = 0을 기준으로 max한 값을 찾아라
#결과가 value값과 max인 index값 두개로 나옴.
print('Max: ', t.max(dim = 0)[0]) #위의 두 값 중 value값이 [0]
print('Argmax:', t.max(dim = 0)[1]) #위의 두 값 중 index값이 [1]

print(t.max(dim = 1)) #axis = 1을 기준으로 max한 값을 찾아라
print(t.max(dim = -1))

tensor([[1., 2.],
        [3., 4.]])
tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max:  tensor([3., 4.])
Argmax: tensor([1, 1])
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


In [38]:
#view(numpy->reshape)
t = np.array([[[0,1,2],
              [3,4,5]],
              
              [[6,7,8],
              [9,10,11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

print(ft.view([-1, 3])) #앞엔 모르겠고 뒤의 차원은 3개를 가질래.
print(ft.view([-1, 3]).shape) #그렇게 바꾸고 나니까 나온 shape

print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape) #결국 다 12개의 element가 들어있다.

torch.Size([2, 2, 3])
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])
tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [42]:
#squeeze(쥐어짜다.)
#자동으로 원하는 dim이 1인 경우를 없어준다. 
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape) #(3,1)의 1인 dimension은 squeeze를 이용하면 날라간다.
print(ft.squeeze())
print(ft.squeeze().shape)

print(ft.squeeze(dim = 0)) #0번째 dimension은 3임, 따라서 그대로 나옴
print(ft.squeeze(dim = 1)) #1번째 dimension은 1임, 따라서 squeeze된다.

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
tensor([0., 1., 2.])
torch.Size([3])
tensor([[0.],
        [1.],
        [2.]])
tensor([0., 1., 2.])


In [51]:
#unsqueeze (내가 원하는 dimension에 1을 넣어준다.)
#여기서는 dimension을 꼭 명시해주어야 함!
ft = torch.Tensor([0,1,2]) #(3,)
print(ft.shape)

print(ft.unsqueeze(dim = 0)) #dimension을 꼭 넣어줘야 함. (1,3)
print(ft.unsqueeze(0).shape) #dimension 0에 1을 넣어줘라.

print(ft.unsqueeze(dim = 1)) #dim 1에 1을 넣어줘라.
print(ft.unsqueeze(1).shape) #(3,1)

print(ft.view(1, -1)) #view는 reshape와 같았음.
print(ft.view(1, -1).shape)

print(ft.unsqueeze(-1)) #dimension = -1: 마지막 dimension -> dimension 1
print(ft.unsqueeze(-1).shape)

torch.Size([3])
tensor([[0., 1., 2.]])
torch.Size([1, 3])
tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
tensor([[0., 1., 2.]])
torch.Size([1, 3])
tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [56]:
#type casting -> tensor의 타입을 바꿔주겠다.
lt = torch.LongTensor([1,2,3,4])
print(lt)

print(lt.float())

bt = torch.ByteTensor([True, False, False, True]) #boolean값을 저장
print(bt)

print(bt.long())
print(bt.float())
'''
bt = (lt == 3)이라면
bt = (0,0,1,0)일 것이다.
왜냐하면 lt가 3인 경우만 참이므로 2번 인덱스만 1이고 나머지는 0
bt는 boolean 값을 저장
'''

tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])
tensor([1, 0, 0, 1], dtype=torch.uint8)
tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


'\nbt = (lt == 3)이라면\nbt = (0,0,1,0)일 것이다.\n왜냐하면 lt가 3인 경우만 참이므로 2번 인덱스만 1이고 나머지는 0\nbt는 boolean 값을 저장\n'

In [59]:
#concatenate (이어붙이는것)
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

print(torch.cat([x, y], dim = 0)) #아래로 이어붙임
print(torch.cat([x, y], dim = 1)) #옆으로 이어붙임

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [63]:
#stacking -> concatenation을 좀더 다루기 쉽게
x = torch.FloatTensor([1,4]) #dimension ->(2,)
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

print(torch.stack([x, y, z])) #리스트 내에는 텐서가 들어있음. 쌓아라!
#dimension -> (3,2) 
print(torch.stack([x, y, z], dim = 1)) #옆으로 쌓아라!
#dimension -> (2, 3)

print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim = 0))
#unsqueeze를 하면 (1,2)가 되고 그다음 cat하면 똑같은 결과가 나온다.

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [65]:
#ones and zeros
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

print(torch.ones_like(x)) #x와 똑같은 shape로 1로 채워라
print(torch.zeros_like(x)) #x와 똑같은 shape로 0로 채워라

tensor([[0., 1., 2.],
        [2., 1., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [67]:
#inplace operation
x = torch.FloatTensor([[1,2], [3,4]])
print(x.mul(2.))
print(x)
print(x.mul_(2.)) #결과값이 x에 들어감
print(x) #다시 프린트했을 때 x값이 들어가졌음

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
